//profile actions
export const SET_USERS_COUNT = 'SET_USERS_COUNT';
export const TOGGLE_PLAYERS_FORM_EDITING = 'TOGGLE_PLAYERS_FORM_EDITING';
export const SET_GAME_CHEMA = 'SET_GAME_CHEMA';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_ACTIVE_GAME = 'SET_ACTIVE_GAME';
export const WRITE_ROUND_SCTATISTIC = 'WRITE_ROUND_SCTATISTIC';
export const PLAYER_PLAYED = 'PLAYER_PLAYED';
export const RESET_CIRCLE = 'RESET_CIRCLE';
export const MINUS_HEALTH = 'MINUS_HEALTH';
export const ADD_BAF = 'ADD_BAF';
export const PLAYER_DIED = 'PLAYER_DIED'; 
export const SET_RESULT_TABLE = 'SET_RESULT_TABLE';  